### PR TITLE
Feature/subseasonal mpmd plots fix

### LINKED ISSUE #561: subseasonal: Address Bugzilla 1547 - MPMD processes share the same working directory
From NCO's Bugzilla 1547

> Multiple jobs use shared working directory for MPMD. Please modify the scripts to have isolated working directory for each process. 
> 
> In the case of extreme IO, please work with NCO/GDIT for the best approach.

More information can be found [here](https://docs.google.com/document/d/12UlvHV89xm_Y6_ayVjFngHQ8I0y77Y_3VJYgzLvLbak/edit).

**Suspected subseasonal Jobs Using MPMD**

- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_31days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_90days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_31days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_90days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_31days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_90days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_31days.sh
- [ ] plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_90days.sh
- [x] stats/subseasonal/jevs_subseasonal_cfs_grid2grid_stats.sh
- [x] stats/subseasonal/jevs_subseasonal_cfs_grid2obs_stats.sh
- [x] stats/subseasonal/jevs_subseasonal_gefs_grid2grid_stats.sh
- [x] stats/subseasonal/jevs_subseasonal_gefs_grid2obs_stats.sh

### PR DESCRIPTION
**Pull request by ShannonShields-NOAA**
<b>Note to developers: You must use this PR template!</b>

## Description of Changes

> Please include a summary of the changes and the related GitHub issue(s). Please also include relevant motivation and context.
This PR includes output directory changes for subseasonal plotting scripts to address the MPMD bugzilla 1547 (Issue #561).
## Developer Questions and Checklist
* Is this a high priorty PR? If so, why and is there a date it needs to be merged by?
* Not exactly, but it is highly preferred to complete testing before Thanksgiving and before making changes for METplus RC1.
* Do you have any planned upcoming annual leave/PTO?
* No (I am ending my workday at 3pm on 11/22)
* Are there any changes needed for when the jobs are supposed to run?
* No
  
- [ ] The code changes follow [NCO's EE2 Standards](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf).
- [ ] Developer's name is removed throughout the code and have used `${USER}` where necessary throughout the code.
- [ ] References the feature branch for `HOMEevs` are removed from the code.
- [ ] J-Job environment variables, COMIN and COMOUT directories, and output follow what has been [defined](https://docs.google.com/document/d/1JWg_4q80aYmmAoD21GFjp9R9y5-3w7WGM3-0HJk0Pjs/edit#heading=h.7ysbr191vzu4) for EVS.
- [ ] Jobs over 15 minutes in runtime have restart capability.
- [ ] If applicable, changes in the `dev/drivers/scripts` or `dev/modulefiles` have been made in the corresponding `ecf/scripts` and `ecf/defs/evs-nco.def`? 
- [ ] Jobs contain the approriate file checking and don't run METplus for any missing data.
- [ ] Code is using METplus wrappers structure and not calling MET executables directly.
- [ ] Log is free of any ERRORs or WARNINGs.

## Testing Instructions

> Please include testing instructions for the PR assignee. Include all relevant input datasets needed to run the tests.
Checkout feature branch, link FIXevs, set COMIN to EMC parallel stats directory, and set HOMEevs.
Please run all scripts under dev/drivers/scripts/plots/subseasonal.

### CODE REVIEW

File: scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh [hunk 1]
```diff
@@ -75,27 +75,43 @@ for group in condense_stats filter_stats make_plots tar_images; do
...
-log_dir=$DATA/${VERIF_CASE}_${STEP}/plot_output/${RUN}.${end_date}/logs
-log_file_count=$(find $log_dir -type f |wc -l)
-if [[ $log_file_count -ne 0 ]]; then
-    for log_file in $log_dir/*; do
-	echo "Start: $log_file"
-	cat $log_file
-	echo "End: $log_file"
-    done
-fi
+#log_dir=$DATA/${VERIF_CASE}_${STEP}/plot_output/${RUN}.${end_date}/logs
```
Comment (malloryprow) [inline scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh]: Can remove this section since it is commented out.

File: ush/subseasonal/create_METplus_subseasonal_output_dirs.py [hunk 2]
```diff
@@ -120,19 +120,22 @@
...
-                     RUN+'.'+end_date_dt.strftime('%Y%m%d'))
+        os.path.join(working_output_base_dir, 'job_work_dir')
     )
     working_dir_list.append(
         os.path.join(working_output_base_dir,
-                     RUN+'.'+end_date_dt.strftime('%Y%m%d'),
-                     'logs')
+                     RUN+'.'+end_date_dt.strftime('%Y%m%d'))
     )
+    #working_dir_list.append(
```
Comment (malloryprow) [inline ush/subseasonal/create_METplus_subseasonal_output_dirs.py]: Can remove this section since it is commented out.

File: scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh (hunk 1 above)
Comment (ShannonShields-NOAA) [reply scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh]: @malloryprow Oops, sorry, I forgot about my commented out code. After I'm done eating lunch, I will go through the scripts and remove the old code. I'll let you know when I'm done with that.

File: ush/subseasonal/subseasonal_plots.py [hunk 3]
```diff
@@ -78,14 +83,22 @@
...
+                                      'tar_files', VERIF_TYPE)
+if JOB_GROUP == 'make_plots':
+    logging_dir = os.path.join(job_work_images_dir, 'logs')
+elif JOB_GROUP == 'tar_images':
+    logging_dir = os.path.join(VERIF_TYPE_tar_dir, 'logs')
+else:
+    logging_dir = os.path.join(job_work_dir, 'logs')
+if not os.path.exists(logging_dir):
+    os.makedirs(logging_dir)
+#job_output_dir = os.path.join(plot_output_dir, RUN+'.'+end_date,
```
Comment (malloryprow) [inline ush/subseasonal/subseasonal_plots.py]: Commented out here and line 86

File: scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh (hunk 1 above)
Comment (ShannonShields-NOAA) [reply scripts/plots/subseasonal/exevs_subseasonal_grid2grid_plots.sh]: Done!

File: ush/subseasonal/create_METplus_subseasonal_output_dirs.py (hunk 2 above)
Comment (ShannonShields-NOAA) [reply ush/subseasonal/create_METplus_subseasonal_output_dirs.py]: Done!

File: ush/subseasonal/subseasonal_plots.py (hunk 3 above)
Comment (ShannonShields-NOAA) [reply ush/subseasonal/subseasonal_plots.py]: Done!

**Comment by ShannonShields-NOAA** [comment]
@malloryprow All commented out/old code has been removed. Thank you for catching that! Due to working extra time earlier this week, I only have half an hour left to my workday, and this testing will take some time in order to be thorough, so let's pick this back up next week on Monday.

**Comment by ShannonShields-NOAA** [comment]
@malloryprow I have checked through the weekend prep and stat files for the EVS parallel and confirmed all is set (the disk quota exceedance over the weekend did not have a meaningful impact). So as long as today's prep and stats run fine (which I am monitoring), then we will be able to test this PR around noon/after the METplus telecon.

**Comment by malloryprow** [comment]
Sounds good! Thanks for checking! I'm glad the stmp issues didn't cause a major impact to subseasonal.

**Comment by ShannonShields-NOAA** [comment]
@malloryprow Prep and stats ran as they should for today's parallel jobs; we are set for this PR testing!

**Comment by malloryprow** [comment]
Al jobs for testing have been submitted! COMOUT is /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/evs/v2.0/plots/subseasonal/atmos.20241123.

### 1. jevs_subseasonal_grid2grid_pres_lvls_plots_31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.o207471711
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.207471711.dbqs01

### 2. jevs_subseasonal_grid2grid_pres_lvls_plots_90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_pres_lvls_plots_90days.o207471721
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_pres_lvls_plots_31days.207471711.dbqs01

### 3. jevs_subseasonal_grid2grid_sea_ice_plots_31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_31days.o207471820
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sea_ice_plots_31days.207471820.dbqs01

### 4. jevs_subseasonal_grid2grid_sea_ice_plots_90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sea_ice_plots_90days.o207471834
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sea_ice_plots_90days.207471834.dbqs01

### 5. jevs_subseasonal_grid2grid_sst_plots_31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_31days.o207472067
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sst_plots_31days.207472067.dbqs01

### 6. jevs_subseasonal_grid2grid_sst_plots_90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_sst_plots_90days.o207472132
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_sst_plots_90days.207472132.dbqs01

### 7. jevs_subseasonal_grid2grid_temp_plots_31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_31days.o207472194
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_temp_plots_31days.207472194.dbqs01

### 8. jevs_subseasonal_grid2grid_temp_plots_90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2grid_temp_plots_90days.o207472259
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2grid_temp_plots_90days.207472259.dbqs01

### 9. jevs_subseasonal_grid2obs_prepbufr_plots_31days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_31days.o207472351
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2obs_prepbufr_plots_31days.207472351.dbqs01

### 10. jevs_subseasonal_grid2obs_prepbufr_plots_90days
**Log File:** /lfs/h2/emc/vpppg/noscrub/mallory.row/verification/EVS_PRs/pr611/EVS/dev/drivers/scripts/plots/subseasonal/jevs_subseasonal_grid2obs_prepbufr_plots_90days.o207472380
**DATA:** /lfs/h2/emc/stmp/mallory.row/evs_test/prod/tmp/jevs_subseasonal_grid2obs_prepbufr_plots_90days.207472380.dbqs01

**Comment by ShannonShields-NOAA** [comment]
@malloryprow and @AliciaBentley-NOAA I have thoroughly checked all of the output for each plot job (like making sure the individual job numbers match between plot_job_scripts and plot_output/job_work_dir) and everything looks correct. I quickly checked the plot tar files and confirmed that nothing looks out of place with the plots. This PR should be set to merge.

**Review by malloryprow — APPROVED** [review]
Changes are good and testing successful.

**Review by AliciaBentley-NOAA — APPROVED** [review]
I have reviewed the changes in this PR and think that they look great! Test results confirm this. Please merge into develop when you are ready. Thanks!

@ShannonShields-NOAA @malloryprow
